# -*- coding: utf-8 -*-
"""Application.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SpgeVWmFB-SzAd5rr1Yt66sYrQVjWIQT
"""

#@title Welcome to our application launcher ! Please execute the code and follow the instructions
# Import necessary libraries
import os
import requests
from zipfile import ZipFile
from io import BytesIO
import subprocess
import sys

# Function to install Python packages using pip
def install(package):
    # Using subprocess to call pip install for the package
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

# URL to download the GitHub repository as a zip file
zip_url = 'https://codeload.github.com/Leorongier/Orange_project/zip/refs/heads/main'

# Function to download and extract the project from GitHub
def setup_project(zip_url):
    # Sending a request to the provided URL to download the zip file
    response = requests.get(zip_url)
    # Extracting the content of the zip file
    with ZipFile(BytesIO(response.content)) as thezip:
        thezip.extractall()

# Execute the function to setup the project
setup_project(zip_url)

# Install necessary Python packages - sacremoses and streamlit
install('sacremoses')
install('streamlit')

# Execute the command to run the Streamlit app and open a localtunnel
command = "streamlit run Orange_project-main/CEFR_Classifier_French/app.py & npx localtunnel --port 8501"
# Start the subprocess and capture its output
process = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

# Read the command output line by line
url = ""
for line in process.stdout:
    decoded_line = line.decode("utf-8")
    # Look for the line that contains the localtunnel URL
    if "your url is:" in decoded_line:
        url = decoded_line.strip()
        break

# Print the instructions for accessing the Streamlit app
print("Your public IP address is:", ip_address)
print("Please copy this IP address and paste it on the following web page:")
print(url)
print("After pasting the IP address, submit the form to access the application.")