# -*- coding: utf-8 -*-
"""Application.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SpgeVWmFB-SzAd5rr1Yt66sYrQVjWIQT
"""

import os
import requests
from zipfile import ZipFile
from io import BytesIO
import subprocess
import sys

# Fonction pour installer des packages
def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

# URL pour télécharger le fichier zip du projet depuis GitHub
zip_url = 'https://codeload.github.com/Leorongier/Orange_project/zip/refs/heads/main'

# Fonction pour télécharger et extraire l'archive du projet
def setup_project(zip_url):
    print("Téléchargement du projet...")
    response = requests.get(zip_url)
    with ZipFile(BytesIO(response.content)) as thezip:
        thezip.extractall()
    print("Projet téléchargé et extrait.")

# Exécutez la fonction de configuration
setup_project(zip_url)

# Installer sacremoses et streamlit
install('sacremoses')
install('streamlit')

print("Installation terminée.")

